ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls")),
    path("",include("mainshop.urls")),
    path("cart/",include("cart.urls")),
    path("orders/",include("orders.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/logout/",views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path('add_to_cart/<int:product_id>/',views.AddToCartView.as_view(),name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path("remove_cart/<int:product_id>/", views.RemoveFromCartView.as_view(), name="remove_cart"),
    path("remove_cart_all/<int:product_id>/", views.RemoveCartView.as_view(), name="remove_cart_all"),
    
    path("favourite_list/", views.FavouriteView.as_view(), name="favourite_list"),
    path("remove_favourite/<int:product_id>/", views.RemoveFromFavView.as_view(), name="remove_favourite"),
    path('add_favourites/<int:product_id>/',views.AddFavouriteView.as_view(), name='add_favourites'),

    path('checkout/',views.CheckoutView.as_view(),name="checkout"),
]

mainshop/urls.py
from django.urls import path
from mainshop import views


urlpatterns = [
    
    path("",views.HomeView.as_view(),name="home"),
    path('featured-products/', views.FeaturedProductsView.as_view(), name='featured-products'), 
    path('featured-products/<slug:category_slug>/', views.FeaturedProductsView.as_view(),name='featured-products-by-category'),  
    path('ajax-featured-products/<slug:category_slug>/', views.ajax_featured_products, name='ajax-featured-products'),
    path("product-list/",views.ProductListView.as_view(),name="product-list"),
    path("product-by-category/<int:category_id>/",views.PostByCategoryView.as_view(),name="product-by-category"),
    path("product-by-brand/<int:brand_id>/",views.PostByBrandView.as_view(),name="product-by-brand"),
    path("product-detail/<int:pk>/",views.ProductDetailView.as_view(),name="product-detail"),
    path("product-search/",views.ProductSearchView.as_view(),name="product-search"),
    path("newsletter/",views.NewsletterView.as_view(),name="newsletter"),
    path("contact/",views.ContactView.as_view(),name="contact"),
    path("flash-sale/",views.FlashSaleView.as_view(),name="flash-sale"),
    path("about/",views.AboutView.as_view(),name="about"),
    path('submit_review/<int:product_id>/',views.submit_review,name='submit_review'),
   

]

mainshop/models.py
from django.db import models
from django.db.models import Avg
from accounts.models import Account

class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Category(TimeStampModel):
    cat_name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    description = models.TextField(blank=True)
    cat_image = models.ImageField(upload_to="post_images/%Y/%m/%d",blank=True)

    def __str__(self):
        return self.cat_name

class Brand(TimeStampModel):
    brand_name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    brand_image = models.ImageField(upload_to="brand_images/%Y/%m/%d",blank=True)

    def __str__(self):
        return self.brand_name


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    price = models.IntegerField()
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_sale = models.BooleanField(default=False) 
    discount = models.DecimalField(max_digits=5,decimal_places=2,default=0)

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    

    def sale_price(self):
        discount_amount = (self.price * self.discount) / 100
        saleprice = self.price - discount_amount
        return saleprice


    def __str__(self):
        return self.product_name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/%Y/%m/%d', blank=False)

    def __str__(self):
        return f"Image for {self.product.product_name}"

class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    
    def __str__(self):
        return self.name

class Newsletter(TimeStampModel):
    email = models.EmailField()

    def __str__(self):
        return self.email

class ReviewRating(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    subject = models.CharField(max_length=100,blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    user_image = models.ImageField(upload_to="post_images/%Y/%m/%d",blank=True)
    ip = models.CharField(max_length=20, blank=True) 
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

mainshop/forms.py
from django_summernote.widgets import SummernoteWidget
from django import forms
from mainshop.models import Product,Contact,Newsletter,ReviewRating

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = "__all__"

class Newsletterform(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = "__all__"

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'rating', 'review', 'user_image']

mainshop/views.py
from django.shortcuts import render
from django.urls import reverse
from mainshop.models import Product , Category , Brand,Newsletter,Contact, ReviewRating
from django.views.generic import ListView,TemplateView,DetailView,View
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from mainshop.forms import Newsletterform,ContactForm, ReviewForm
from django.contrib import messages
from django.shortcuts import redirect, render
from cart.models import CartItem,Favourite
from django.contrib.auth.decorators import login_required

class HomeView(ListView):
    model = Product
    template_name = "mainshop/home.html"
    context_object_name = "products"

    def get_queryset(self):
        return Product.objects.filter(is_available=True, stock__gte=1).order_by("-created_date")[:12]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Ensure user is authenticated before accessing user-related attributes
        context["is_authenticated"] = user.is_authenticated
        if user.is_authenticated:
            context["username"] = user.username

        return context

class FeaturedProductsView(ListView):
    model = Product
    template_name = 'mainshop/featured_products.html'  # Make sure the template is correct
    context_object_name = 'products'
    paginate_by = 12  # Pagination, 12 products per page

    def get_queryset(self):
        category_slug = self.kwargs.get("category_slug", None)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            return Product.objects.filter(is_available=True, category=category).order_by("-created_date")
        return Product.objects.filter(is_available=True).order_by("-created_date")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['featured_categories'] = Category.objects.all()
        context['selected_category'] = self.kwargs.get("category_slug", 'all')
        return context


def ajax_featured_products(request, category_slug):
    if category_slug == 'all':
        products = Product.objects.filter(is_available=True).order_by("-created_date")[:12]
    else:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(is_available=True, category=category).order_by("-created_date")[:12]
    
    products_data = [
        {
            'product_name': product.product_name,
            'price': float(product.price) if product.price else 0.0,
            'sale_price': float(product.sale_price()) if product.is_sale else 0.0,  # Call the method correctly
            'discount': float(product.discount) if product.discount else 0.0,
            'is_sale': product.is_sale,
            'image_url': product.images.first().image.url if product.images.exists() else '',
            'category_slug': product.category.slug,
            'stock': product.stock,
            'pk': product.pk,
        }
        for product in products
    ]
    return JsonResponse({'products': products_data})




class ProductListView(ListView):
    model = Product
    template_name = "mainshop/store/store.html"
    context_object_name = "products"
    paginate_by = 12

    def get_queryset(self):
        queryset = Product.objects.filter(is_available=True)
        sort = self.request.GET.get("sort")

        if sort == "price_asc":
            queryset = queryset.order_by("price")  # Low to high
        elif sort == "price_desc":
            queryset = queryset.order_by("-price")  # High to low
        elif sort == "sale_product":
            queryset = Product.objects.filter(is_available=True,is_sale=True).order_by("-created_date")


        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product_count"] = self.get_queryset().count()
        context["request"] = self.request  # Pass request to template
        return context

class PostByCategoryView(ListView):
    model = Product
    template_name = "mainshop/store/store.html"
    context_object_name = "products"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get("category_id")
        if category_id:
            queryset = queryset.filter(
                is_available=True,
                category__id=category_id
            ).order_by("-created_date")
        
        sort_option = self.request.GET.get('sort')
        if sort_option == 'price_asc':
            queryset = queryset.order_by('price')
        elif sort_option == 'price_desc':
            queryset = queryset.order_by('-price')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['selected_category'] = self.kwargs.get("category_id", 'all')
        context['product_count'] = self.get_queryset().count()
        return context



class PostByBrandView(ListView):
    model = Product
    template_name = "mainshop/store/store.html"
    context_object_name = "products"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        brand_id = self.kwargs.get("brand_id")
        if brand_id:
            queryset = queryset.filter(
                is_available=True,
                brand__id=brand_id
            ).order_by("-created_date")
        
        sort_option = self.request.GET.get('sort')
        if sort_option == 'price_asc':
            queryset = queryset.order_by('price')
        elif sort_option == 'price_desc':
            queryset = queryset.order_by('-price')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Brand.objects.all()
        context['selected_brand'] = self.kwargs.get("brand_id", 'all')
        context['product_count'] = self.get_queryset().count()
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = "mainshop/product_detail/main_productDetail.html"
    context_object_name = "product"

    def get_queryset(self):
        query = super().get_queryset()
        query = query.filter(is_available=True)
        return query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        related_products = Product.objects.filter(category=product.category).exclude(id=product.id)[:4]
        context['related_products'] = related_products
        review = ReviewRating.objects.filter(product_id=product.id, status=True)

        if self.request.user.is_authenticated:
            cart_items = CartItem.objects.filter(cart__user=self.request.user).values_list('product_id',flat=True)
            fav_items = Favourite.objects.filter(user=self.request.user).values_list('product_id',flat=True)

            context['cart_items'] = cart_items
            context['fav_items'] = fav_items


        else:
            context['cart_items'] =  set()
            context['fav_items'] =  set()

        return context

class ProductSearchView(View):
    template_name = "mainshop/store/store.html"

    def get(self, request, *args, **kwargs):
        query = request.GET.get("query", "")  # Use .get() to avoid KeyError
        product_list = Product.objects.filter(
            (Q(product_name__icontains=query) |
             Q(description__icontains=query)) &
            Q(is_available=True)
        ).order_by("-created_date")
        
        # Pagination start
        page = request.GET.get("page", 1)  # Default page is 1
        paginate_by = 10
        paginator = Paginator(product_list, paginate_by)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        # Pagination end

        return render(
            request,
            self.template_name,
            {"page_obj": products, "query": query},
        )
     
class NewsletterView(View):
    def post(self, request):
        is_ajax = request.headers.get("X-Requested-With")
        if is_ajax == "XMLHttpRequest":
            form = Newsletterform(request.POST)
            if form.is_valid():
                email = form.cleaned_data.get("email")
                
                # Check for duplicate email
                if Newsletter.objects.filter(email=email).exists():
                    return JsonResponse(
                        {
                            "success": False,
                            "message": "This email is already subscribed to the newsletter.",
                        },
                        status=400,
                    )
                
                # Save the form if no duplicates
                form.save()
                return JsonResponse(
                    {
                        "success": True,
                        "message": "Successfully Subscribed to Newsletter",
                    },
                    status=201,
                )
            else:
                return JsonResponse(
                    {
                        "success": False,
                        "message": "Cannot Subscribe to the Newsletter. Please check your input.",
                    },
                    status=400,
                )
        else:
            return JsonResponse(
                {
                    "success": False,
                    "message": "Cannot process, must be an AJAX XMLHttpRequest.",
                },
                status=400,
            )

class ContactView(View):

templates/mainshop/product_detail/banner.html
<!-- Breadcrumb Section Begin -->
{% load static %}
<section class="breadcrumb-section set-bg" data-setbg="{% static 'mainshop/assets/img/banner/Banner.png' %}" >
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2 style="color: rgb(88 56 56); margin-left: 100px; " >N-ERB BEAUTY</h2>
                    <div class="breadcrumb__option">
                        <a href="/" style="color: rgb(255, 255, 255); margin-left: 100px;">Home</a>
                        <span style="color: rgb(255, 247, 247); ">Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

templates/mainshop/product_detail/bottom.html
{% load static %}
<div class="col-lg-12">
    <div class="product__details__tab">
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
                    aria-selected="true">Description</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
                    aria-selected="false"> Product Information</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab"
                    aria-selected="false">Reviews <span>({{ product.reviewrating_set.count }})</span></a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                <div class="product__details__tab__desc">
                    <h6>Products Infomation</h6>
                    <p>{{ product.description|striptags|linebreaksbr }}</p>
                </div>
            </div>
            <div class="tab-pane" id="tabs-2" role="tabpanel">
                <div class="product__details__tab__desc">
                    <h6>Products Infomation</h6>
                    <p>{{ product.description|safe|linebreaksbr }}</p>
                </div>
            </div>
            <div class="tab-pane" id="tabs-3" role="tabpanel">
                <div class="product__details__tab__desc">
                    <h3 style="font-family: fantasy; "> Write a Review ✍️</h3> <br>
               <form action="{% url 'submit_review' product.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- rating  starts-->
                 <label for=rate"">How do you rate this product ?</label><br>
                 <div class="rate">
                    <input type="radio" name="rating" id="rating10" value="5" required> <label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required> <label for="rating9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required> <label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required> <label for="rating7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating6" value="3" required> <label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required> <label for="rating5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required> <label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required> <label for="rating3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required> <label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="0.5" required> <label for="rating1" title="0.5" class="half"></label>
                 </div><br>
                 

       
            
        
        <textarea name="review" rows="4" style="width: 1000px;"></textarea><br>
        <label for="image">Upload Image:</label>
        <input type="file" name="user_image" accept="image/*"><br><br>
       
        
            <input type="submit" value="Submit Review" class="btn btn-primary">
    
    </form>
    <br></div> 
<hr>

<div class="tab-content">
<div class="col-md-9">
    <header class="section-heading">
    <h3 style="font-family: fantasy; "> Customer Reviews ({{ product.reviewrating_set.count }}) </h3> 
    <br>
    <span class="rating-star11">
    <h3>{{ product.averageReview }}</h3>
    <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5  and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5  and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5  and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5  and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5  and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
    <span>{{ product.reviewrating_set.count }} reviews</span>

    </span>

            </header>
            <br><hr>
            {% for review in product.reviewrating_set.all %}
            <article class="box mb-3">
                <div class="icontext w-100 d-flex align-items-center">
                    <!-- Profile Image -->
                    <img src="{% static 'mainshop/assets/img/profile.jpg' %}" class="img-xs icon rounded-circle" style="width: 50px; margin-right: 10px;">
                    <!-- Username and Date -->
                    <div class="text">
                        <h6 class="mb-1">{{ review.user.first_name }} {{ review.user.last_name }}</h6>
                        <span class="date text-muted float-md-right">{{ review.created_at }}</span>  
                    </div>
                </div> 
                <div class="mt-2 rating-star">
                    <span>
                <i class="fa fa-star{% if product.averageReview == 0.5 %}-half-o{% elif product.averageReview < 1 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview == 1.5 %}-half-o{% elif product.averageReview < 2 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview == 2.5 %}-half-o{% elif product.averageReview < 3 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview == 3.5 %}-half-o{% elif product.averageReview < 4 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview == 4.5 %}-half-o{% elif product.averageReview < 5 %}-o {% endif %}" aria-hidden="true"></i></span>
                </div>
                
                <div class="mt-3">
                    <p>{{ review.review }}</p>  
                </div>
                {% if review.user_image %}
                <div class="mt-3">
                    <img src="{{ review.user_image.url }}" alt="{{ review.user.username }}" width="200px">
                </div>
                {% endif %}
            </article>
            {% endfor %}
        </div> 
    </div>
    

    <!-- <div class="comments-area">
        <h4>{{ product.reviewrating_set.count }} Reviews</h4>
       {% for review in product.reviewrating_set.all %}
    
        <div class="comment-list">
           <div class="single-comment justify-content-between d-flex">
              <div class="user justify-content-between d-flex">
                 <div class="thumb">
                    <img src="{% static 'mainshop/assets/img/profile.jpg' %}" alt="#" width="30px" style="border-radius: 50%;">
                    <div class="d-flex align-items-center">
                        <h5>
                           <a href="#">{{ review.user.username }}</a>
                        </h5>
                        <p class="date">{{ review.created_at|date:"F j, Y, g:i a" }} </p>
                     </div>
                 </div>
                
                 <div class="desc">
                    <p class="comment"> {{ review.review }}</p>
                    <div class="d-flex justify-content-between">

                      
                       {% if review.user_image %}
                       <div class="thumb">

                        <img src="{{ review.user_image.url }}" alt="{{ review.user.username }}" width="50px">
                        
                    </div>
                    {% endif %}
                    </div>
                 </div>
              </div>
           </div>
        </div>
    
       {% endfor %}
    
     </div> -->



            </div>
        </div>
    </div>
</div>

templates/mainshop/product_detail/top_right.html
<div class="col-lg-6 col-md-6">
    {% if product.is_sale %}
    
    <div class="badge text-light position-absolute" style=" margin-top: -40px; width: 100px; background-color: red; height: 30px; font-size:large;"> On Sale </div>
   
    <div class="product__details__text">
        
        <h6 style=" font-size:x-large; font-weight: bold; color: rgb(251, 0, 0);">{{ product.discount }} % off</h6>
    
        <h3>{{ product.product_name }}</h3>
        <div class="product__details__rating">
            <span>
                <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5  and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5  and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5  and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5  and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5  and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                </span>
                <span>{{ product.reviewrating_set.count }} reviews</span>
        </div>
        
        <div class="product__details__price">Rs. {{ product.sale_price }} &nbsp; <strike> Rs{{ product.price }}</strike></div>
       
        {% else %}
       
     <div class="product__details__text">
         <h3>{{ product.product_name }}</h3>
            <div class="product__details__rating">
                <span>
                <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5  and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5  and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5  and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5  and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5  and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                </span>
                <span>{{ product.reviewrating_set.count }} reviews</span>
            </div>
            
       
        <div class="product__details__price">Rs. {{ product.price }}</div>
        {% endif %}

        <p >{{ product.description| striptags |truncatewords:50 }}</p>
        

        
        {% if product.stock <= 0 %}
        
        <button class="primary-btn" style="border: none; cursor: not-allowed; opacity: 0.6; margin-top: 40px; background-color: red;">
            Out of Stock
        </button>
       
        {% elif product.id in cart_items %}
       
       <button class="primary-btn" style="border: none; margin-left: -10px; background-color: red;" disabled >Added to Cart</button>
        
        {% elif product.id not in cart_items %}

        <form method="POST" action="{% url 'add_to_cart' product.id %}" style="width:500px;">
            {% csrf_token %}
            <button type="submit" class="primary-btn" style="border: none;">
                ADD TO CART
            </button>
        </form>
      
       
        {% endif %}
        
        {% if product.id in fav_items %}
        <div style="width: 300px; margin-top: -57px; margin-left: 180px; ">
            <button class="primary-btn" style="border: none; background-color: gray;" disabled>Added to Favourites</button>
        </div>
        
        {% else %}
        <form method="POST" action="{% url 'add_favourites' product.id %}" style="width: 500px; margin-top: -57px; margin-left: 180px; ">
            {% csrf_token %}
            <button type="submit" class="primary-btn" style="border: none;  background-color: palevioletred;">
                ADD TO FAVOURITES
            </button>
        </form>
        {% endif %}

       
        <ul>
            <li><b>Availability</b> 
            <span>
            {% if product.is_available %}
                Available
            {% else %}
                Not Available
            {% endif %}
            
            </span></li>
            <li><b>Shipping</b> <span> 01 day shipping | <samp> Free delivery every Friday </samp></span></li>
            <li><b>Weight</b> <span>0.5 kg</span></li>
            <li><b>Share on</b>
                <div class="share">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </li>
        </ul>
    </div>
</div>